export const buildLogs = [
  { type: "info", text: "Running build in Washington, D.C., USA (East) – iad1" },
  { type: "info", text: "Build machine configuration: 4 cores, 8 GB" },
  { type: "info", text: "Cloning github.com/jailson-silva-py/this-project (Branch: main, Commit: 2o43a1)" },
  { type: "success", text: "Cloning completed: 664.000ms" },
  { type: "info", text: "Restored build cache from previous deployment" },
  { type: "info", text: 'Running "vercel build"' },
  { type: "info", text: "Vercel CLI 37.0.0" },
  { type: "info", text: "Installing dependencies..." },
  { type: "info", text: "Detected pnpm" },
  { type: "info", text: "Packages: +312" },
  { type: "success", text: "Done in 8.1s" },
  { type: "info", text: "Detected Next.js version: 14.2.5" },
  { type: "info", text: "Running 'pnpm run build'" },
  { type: "info", text: "▲ Next.js 14.2.5" },
  { type: "info", text: "Creating an optimized production build ..." },
  { type: "error", text: "Failed to compile." },
  { type: "error", text: "" },
  { type: "error", text: "./app/dashboard/page.tsx" },
  { type: "error", text: "Error: workflow overflow detected" },
  { type: "error", text: "→ pipeline exceeded the maximum concurrent tasks (128/64)" },
  { type: "error", text: "→ needing this dev full-stack: Jailson S. Pereira" },
  { type: "error", text: "Error: Command 'pnpm run build' exited with 1" }
];